export const GET_ESCALATIONS_SUCCESS = 'GET_ESCALATIONS_SUCCESS';
export const CHANGE_ESCALATION_STATUS_SUCCESS = 'CHANGE_ESCALATION_STATUS_SUCCESS';
export const ESCALATION_ERROR = 'ESCALATION_ERROR';